name: ashesi_engage
description: An e-participation platform for enhancing student engagement and decision-making at Ashesi University.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  tuple: ^2.0.2  # Added for QuillEditor text styles
  cloud_functions: ^5.0.0  # Added for Firebase Cloud Functions

  provider: ^6.0.5
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  timeago: ^3.7.0  # For relative timestamps
  flutter_scrolling_fab_animated: ^0.1.5
  animations: ^2.0.11
  go_router: ^13.2.0
  shimmer_animation: ^2.1.0
  flutter_quill: ^10.8.5
  flutter_quill_extensions: ^10.8.5
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.1
  mockito: ^5.4.5
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.3
  webview_flutter: ^4.10.0
  intl: ^0.19.0
  firebase_database: ^11.3.2
  firebase_storage: ^12.4.2
  image: ^4.5.2
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.3
  image_cropper: ^9.0.0
  firebase_app_check: ^0.3.2+2
  firebase_vertexai: ^1.2.0
  flutter_markdown: ^0.7.6+2
  collection: ^1.19.0
  universal_html: ^2.2.4  # For web-specific functionality
  js: ^0.6.7  # For JavaScript interop
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.5 # Added for calendar integration
  add_2_calendar: ^3.0.1
  table_calendar: ^3.1.3
  uuid: ^4.3.3  # Added for generating unique IDs
  rxdart: ^0.28.0
  fl_chart: ^0.65.0
  googleapis_auth: ^2.0.0
  connectivity_plus: ^4.0.2
  http: ^1.3.0
  app_links: ^3.5.0
  package_info_plus: ^8.3.0  # Updated version to resolve conflict

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  go_router_builder: ^2.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/ashesi-engage-3b79286765a6.json
